-- MySQL Script generated by MySQL Workbench
-- Sun May 24 19:58:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Pizzaria` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzaria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzaria` ;

-- -----------------------------------------------------
-- Table `mydb`.`caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`caixa` (
  `cnpj` VARCHAR(25) NOT NULL,
  `totalDiario` DOUBLE NOT NULL,
  `TotalMensal` DOUBLE NOT NULL,
  `dinheiroEmCaixa` DOUBLE NOT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Mesa` (
  `idmesa` INT NOT NULL,
  `NPessoas` VARCHAR(45) NOT NULL,
  `caixa_cnpj` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idmesa`),
  CONSTRAINT `fk_Mesa_caixa`
    FOREIGN KEY (`caixa_cnpj`)
    REFERENCES `Pizzaria`.`caixa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Pedido` (
  `idPedido` INT NOT NULL auto_increment,
  `Pedido` VARCHAR(150) NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  `obervacao` VARCHAR(45),
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`cliente` (
  `idcliente` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `Promoção` VARCHAR(45) NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Mesa_idmesa` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  CONSTRAINT `fk_cliente_Pedidio1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Pizzaria`.`Pedido` (`idPedido`)
    ON DELETE cascade
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_Mesa1`
    FOREIGN KEY (`Mesa_idmesa`)
    REFERENCES `Pizzaria`.`Mesa` (`idmesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa_has_Pedidio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Mesa_has_Pedido` (
  `Mesa_idmesa` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `hora` datetime NOT NULL,
  PRIMARY KEY (`Mesa_idmesa`, `Pedido_idPedido`),
  CONSTRAINT `fk_Mesa_has_Pedido_Mesa1`
    FOREIGN KEY (`Mesa_idmesa`)
    REFERENCES `Pizzaria`.`Mesa` (`idmesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mesa_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Pizzaria`.`Pedido` (`idPedido`)
    ON DELETE cascade
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Estoque` (
  `idProduto` INT NOT NULL auto_increment,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(100) NOT NULL,
  `Qtd` INT NOT NULL,
  `Preco` DOUBLE NOT NULL,
  `Total` DOUBLE NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido_has_Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Pedido_has_Estoque` (
  `Pedido_idPedido` INT NOT NULL,
  `Estoque_idProduto` INT NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Estoque_idProduto`),
  CONSTRAINT `fk_Pedido_has_Estoque_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Pizzaria`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idProduto`)
    REFERENCES `Pizzaria`.`Estoque` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
select * from Caixa;
select * from Mesa;
select * from Pedido;
select * from cliente;
select * from mesa_has_pedido;
