/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.comandapizzaria.telas;

import comandapizzaria.Caixa;
import comandapizzaria.Pedido;
import comandapizzaria.PedidoDAO;
import java.util.ArrayList;

/**
 *
 * @author Lucas
 */
public class AfterPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form AfterPrincipal
     */
    public AfterPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_cadastrarpedido = new javax.swing.JPanel();
        jButton_cadastrarpedido = new javax.swing.JButton();
        jButton_voltar = new javax.swing.JButton();
        jPanel_listapedidos = new javax.swing.JPanel();
        jScrollPane_pedidos = new javax.swing.JScrollPane();
        jList_pedidos = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton_editarpedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_valor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_cadastrarpedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_cadastrarpedido.setForeground(new java.awt.Color(255, 0, 0));
        jButton_cadastrarpedido.setText("Cadastrar novo pedido");
        jButton_cadastrarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrarpedidoActionPerformed(evt);
            }
        });

        jButton_voltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_voltar.setForeground(new java.awt.Color(255, 0, 0));
        jButton_voltar.setText("Voltar");
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_cadastrarpedidoLayout = new javax.swing.GroupLayout(jPanel_cadastrarpedido);
        jPanel_cadastrarpedido.setLayout(jPanel_cadastrarpedidoLayout);
        jPanel_cadastrarpedidoLayout.setHorizontalGroup(
            jPanel_cadastrarpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_cadastrarpedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_cadastrarpedido)
                .addContainerGap())
        );
        jPanel_cadastrarpedidoLayout.setVerticalGroup(
            jPanel_cadastrarpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_cadastrarpedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_cadastrarpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_cadastrarpedido, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton_voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel_listapedidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jScrollPane_pedidos.setViewportView(jList_pedidos);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Mostrar Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_editarpedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_editarpedido.setForeground(new java.awt.Color(255, 0, 0));
        jButton_editarpedido.setText("Editar pedido");
        jButton_editarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarpedidoActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor Total:");

        jTextField_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_valorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_listapedidosLayout = new javax.swing.GroupLayout(jPanel_listapedidos);
        jPanel_listapedidos.setLayout(jPanel_listapedidosLayout);
        jPanel_listapedidosLayout.setHorizontalGroup(
            jPanel_listapedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_pedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
            .addGroup(jPanel_listapedidosLayout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_editarpedido)
                .addContainerGap())
            .addGroup(jPanel_listapedidosLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_listapedidosLayout.setVerticalGroup(
            jPanel_listapedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_listapedidosLayout.createSequentialGroup()
                .addComponent(jScrollPane_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_listapedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel_listapedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_editarpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_listapedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_cadastrarpedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_cadastrarpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_listapedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cadastrarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrarpedidoActionPerformed
        chamarCadastrarNovoPedido();
    }//GEN-LAST:event_jButton_cadastrarpedidoActionPerformed

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
        voltarTelaPrincipal();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_editarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarpedidoActionPerformed
        chamarEditaPedido();
    }//GEN-LAST:event_jButton_editarpedidoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        listarProdutos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_valorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfterPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfterPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfterPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfterPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfterPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_cadastrarpedido;
    private javax.swing.JButton jButton_editarpedido;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList_pedidos;
    private javax.swing.JPanel jPanel_cadastrarpedido;
    private javax.swing.JPanel jPanel_listapedidos;
    private javax.swing.JScrollPane jScrollPane_pedidos;
    private javax.swing.JTextField jTextField_valor;
    // End of variables declaration//GEN-END:variables
    int mesa;//variavel id da mesa
    
    //função para chamar a tela de edição de pedido
    private void chamarEditaPedido(){
        EditaPedido ep = new EditaPedido();
        ep.setVisible(true);
        //ep.listar produtos, serve para quando a outra tela aparecer
        //a lista aparecer automaticamente
        ep.listarProdutos();
        dispose();
    }
    
    //função para chamar a tela para o cadastro de um novo pedido
    private void chamarCadastrarNovoPedido(){
        CadastraNovoPedido cnp = new CadastraNovoPedido();
        cnp.mesa = mesa;
        cnp.setVisible(true);
        dispose();
    }
    //função para voltar para a tela de manuseio do pedido(depois da principal)
    private void voltarTelaPrincipal(){
        TelaPrincipal tp = new TelaPrincipal();
        tp.setVisible(true);
        dispose();
    }
    //função que lista os produtos ate então registrados no BD
    //ao ser clicado o botao "mostrar pedido" na Tela
    private void listarProdutos(){
        PedidoDAO pdao = new PedidoDAO();
        //busca pelo id do pedido para manipulação do mesmo no BD
        int id = pdao.buscaIdPedido();
        //estanciando uma nova classe pedido, atribuindo ao mesmo
        //o resultado da pdao.buscaparalistar
        //pda.buscaParaListar = função utilizada aqui para buscar os dados
        //do pedido, atraves do id achado anteriormente
        Pedido p = pdao.BuscaParaListar(id);
        //algumas linhas de codigo abaixo para que na hora de listar 
        //o pedido, o mesmo fique certo, e apareça produto em baixo de produto
        //pois os dados em aux2 é divido nas "/", e atribuido a String[] list
        String[] aux = new String[p.getPedido().size()];
        for (int i = 0; i < aux.length; i++) {
            aux[i] = p.getPedido().get(i);
        }
        String aux2 = aux[0];
        for (int i = 1; i < aux.length; i++) {
            aux2 = aux2 + "/ " + aux[i];
        }
        String[] list = aux2.split("/");
        //passando o float Valor do pedido para String para colocar no campo de TextField
        String t = Float.toString(p.getValor());
        jList_pedidos.setListData(list);
        jTextField_valor.setText(t); 
    }
}
