/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.comandapizzaria.telas;

import comandapizzaria.Caixa;
import comandapizzaria.Cliente;
import comandapizzaria.ClienteDAO;
import comandapizzaria.Mesas;
import comandapizzaria.Pedido;
import comandapizzaria.PedidoDAO;
import java.util.ArrayList;

/**
 *
 * @author Lucas
 */
public class CadastraNovoPedido extends javax.swing.JFrame {

    /**
     * Creates new form CadastraNovoPedido
     */
    public CadastraNovoPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_infoClient = new javax.swing.JPanel();
        jLabel_name = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jLabel_tel = new javax.swing.JLabel();
        jTextField_tel = new javax.swing.JTextField();
        jLabel_promo = new javax.swing.JLabel();
        jCheckBox_promo = new javax.swing.JCheckBox();
        jPanel_pedido = new javax.swing.JPanel();
        jLabel_pizza1 = new javax.swing.JLabel();
        jTextField_pizza1 = new javax.swing.JTextField();
        jLabel_qtd1 = new javax.swing.JLabel();
        jComboBox_qtd1_pizza = new javax.swing.JComboBox<>();
        jLabel_obs = new javax.swing.JLabel();
        jTextField_obs = new javax.swing.JTextField();
        jButton_voltar = new javax.swing.JButton();
        jLabel_pizza2 = new javax.swing.JLabel();
        jLabel_qtd2 = new javax.swing.JLabel();
        jComboBox_qtd2_pizza = new javax.swing.JComboBox<>();
        jTextField_pizza2 = new javax.swing.JTextField();
        jLabel_refri = new javax.swing.JLabel();
        jLabel_qtd3 = new javax.swing.JLabel();
        jComboBox_qtd_refri = new javax.swing.JComboBox<>();
        jTextField_refri = new javax.swing.JTextField();
        jLabel_sobremesa = new javax.swing.JLabel();
        jTextField_sobremesa = new javax.swing.JTextField();
        jLabel_qtd4 = new javax.swing.JLabel();
        jComboBox_qtd_sobremesa = new javax.swing.JComboBox<>();
        jButton_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_infoClient.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "InfoCliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_name.setText("Nome:");

        jLabel_tel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_tel.setText("Telefone:");

        jLabel_promo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_promo.setText("Promoção");

        jCheckBox_promo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_promoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_infoClientLayout = new javax.swing.GroupLayout(jPanel_infoClient);
        jPanel_infoClient.setLayout(jPanel_infoClientLayout);
        jPanel_infoClientLayout.setHorizontalGroup(
            jPanel_infoClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_infoClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_name)
                    .addComponent(jTextField_tel)
                    .addGroup(jPanel_infoClientLayout.createSequentialGroup()
                        .addGroup(jPanel_infoClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_name)
                            .addComponent(jLabel_tel)
                            .addGroup(jPanel_infoClientLayout.createSequentialGroup()
                                .addComponent(jLabel_promo)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_promo)))
                        .addGap(0, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_infoClientLayout.setVerticalGroup(
            jPanel_infoClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoClientLayout.createSequentialGroup()
                .addComponent(jLabel_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_tel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_infoClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_promo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_promo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel_pedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel_pizza1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_pizza1.setText("Pizza:");

        jTextField_pizza1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pizza1ActionPerformed(evt);
            }
        });

        jLabel_qtd1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_qtd1.setText("Quantidade:");

        jComboBox_qtd1_pizza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox_qtd1_pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_qtd1_pizzaActionPerformed(evt);
            }
        });

        jLabel_obs.setText("Obs:");

        jButton_voltar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_voltar.setText("Voltar");
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });

        jLabel_pizza2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_pizza2.setText("Pizza:");

        jLabel_qtd2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_qtd2.setText("Quantidade:");

        jComboBox_qtd2_pizza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox_qtd2_pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_qtd2_pizzaActionPerformed(evt);
            }
        });

        jTextField_pizza2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pizza2ActionPerformed(evt);
            }
        });

        jLabel_refri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_refri.setText("Refrigerante:");

        jLabel_qtd3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_qtd3.setText("Quantidade:");

        jComboBox_qtd_refri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox_qtd_refri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_qtd_refriActionPerformed(evt);
            }
        });

        jTextField_refri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_refriActionPerformed(evt);
            }
        });

        jLabel_sobremesa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_sobremesa.setText("Sobremesa:");

        jTextField_sobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sobremesaActionPerformed(evt);
            }
        });

        jLabel_qtd4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_qtd4.setText("Quantidade:");

        jComboBox_qtd_sobremesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox_qtd_sobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_qtd_sobremesaActionPerformed(evt);
            }
        });

        jButton_cadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_cadastrar.setText("Cadastrar");
        jButton_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_pedidoLayout = new javax.swing.GroupLayout(jPanel_pedido);
        jPanel_pedido.setLayout(jPanel_pedidoLayout);
        jPanel_pedidoLayout.setHorizontalGroup(
            jPanel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_obs)
                    .addComponent(jTextField_pizza1)
                    .addComponent(jTextField_pizza2)
                    .addComponent(jTextField_refri, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_sobremesa)
                    .addGroup(jPanel_pedidoLayout.createSequentialGroup()
                        .addComponent(jButton_voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_cadastrar))
                    .addGroup(jPanel_pedidoLayout.createSequentialGroup()
                        .addGroup(jPanel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_obs)
                            .addGroup(jPanel_pedidoLayout.createSequentialGroup()
                                .addComponent(jLabel_pizza1)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel_qtd1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_qtd1_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_pedidoLayout.createSequentialGroup()
                                .addComponent(jLabel_pizza2)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel_qtd2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_qtd2_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_pedidoLayout.createSequentialGroup()
                                .addComponent(jLabel_refri)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_qtd3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_qtd_refri, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_pedidoLayout.createSequentialGroup()
                                .addComponent(jLabel_sobremesa)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel_qtd4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_qtd_sobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_pedidoLayout.setVerticalGroup(
            jPanel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pedidoLayout.createSequentialGroup()
                .addGroup(jPanel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pizza1)
                    .addComponent(jLabel_qtd1)
                    .addComponent(jComboBox_qtd1_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_pizza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_pizza2)
                    .addGroup(jPanel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_qtd2)
                        .addComponent(jComboBox_qtd2_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jTextField_pizza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_refri)
                    .addComponent(jLabel_qtd3)
                    .addComponent(jComboBox_qtd_refri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_refri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_sobremesa)
                    .addComponent(jLabel_qtd4)
                    .addComponent(jComboBox_qtd_sobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_sobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_obs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_infoClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_infoClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel_pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_promoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_promoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_promoActionPerformed

    private void jComboBox_qtd1_pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_qtd1_pizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_qtd1_pizzaActionPerformed

    private void jTextField_pizza1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pizza1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pizza1ActionPerformed

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
        voltaAfterPrincipal();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrarActionPerformed
        cadastraNovoPedido();
    }//GEN-LAST:event_jButton_cadastrarActionPerformed

    private void jComboBox_qtd2_pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_qtd2_pizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_qtd2_pizzaActionPerformed

    private void jTextField_pizza2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pizza2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pizza2ActionPerformed

    private void jComboBox_qtd_refriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_qtd_refriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_qtd_refriActionPerformed

    private void jTextField_refriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_refriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_refriActionPerformed

    private void jTextField_sobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sobremesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sobremesaActionPerformed

    private void jComboBox_qtd_sobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_qtd_sobremesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_qtd_sobremesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastraNovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastraNovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastraNovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastraNovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastraNovoPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cadastrar;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JCheckBox jCheckBox_promo;
    private javax.swing.JComboBox<String> jComboBox_qtd1_pizza;
    private javax.swing.JComboBox<String> jComboBox_qtd2_pizza;
    private javax.swing.JComboBox<String> jComboBox_qtd_refri;
    private javax.swing.JComboBox<String> jComboBox_qtd_sobremesa;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_obs;
    private javax.swing.JLabel jLabel_pizza1;
    private javax.swing.JLabel jLabel_pizza2;
    private javax.swing.JLabel jLabel_promo;
    private javax.swing.JLabel jLabel_qtd1;
    private javax.swing.JLabel jLabel_qtd2;
    private javax.swing.JLabel jLabel_qtd3;
    private javax.swing.JLabel jLabel_qtd4;
    private javax.swing.JLabel jLabel_refri;
    private javax.swing.JLabel jLabel_sobremesa;
    private javax.swing.JLabel jLabel_tel;
    private javax.swing.JPanel jPanel_infoClient;
    private javax.swing.JPanel jPanel_pedido;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_obs;
    private javax.swing.JTextField jTextField_pizza1;
    private javax.swing.JTextField jTextField_pizza2;
    private javax.swing.JTextField jTextField_refri;
    private javax.swing.JTextField jTextField_sobremesa;
    private javax.swing.JTextField jTextField_tel;
    // End of variables declaration//GEN-END:variables
    
    int mesa;
    //função para voltar a tela
    private void voltaAfterPrincipal(){
        AfterPrincipal ap = new AfterPrincipal();
        ap.setVisible(true);
        dispose();
    }
    //função para limpar os campos de textfields
    private void limpaCampo(){
        jTextField_pizza1.setText("");
        jTextField_pizza2.setText("");
        jTextField_refri.setText("");
        jTextField_sobremesa.setText("");  
    }
    //função responsavel por cadastrar o novo pedido no BD
    private void cadastraNovoPedido(){
        //atribuindo os campos textfields a variaveis
        String nome = jTextField_name.getText();
        String tel = jTextField_tel.getText();
        boolean promo = jCheckBox_promo.getAutoscrolls();
        String obs = jTextField_obs.getText();
        String pizza1 = jTextField_pizza1.getText();
        String pizza2 = jTextField_pizza2.getText();
        String refri = jTextField_refri.getText();
        String sobre = jTextField_sobremesa.getText();
        
        //linhas de codigo abaixo, para preencher o array<String> pedido
        //de forma correta, e também somar o dinheiro total do pedido
        ArrayList<String> pedido = new ArrayList();
        int valor = 0;
        if (!pizza1.isEmpty()) {
            //o +1 é porque o get.selectedIndex pega o primeiro termo e devolve 0
            //o segundo termo e devolve 1, e assim adiante
            int aux = jComboBox_qtd1_pizza.getSelectedIndex()+1;
            valor = 30*aux;
            for (int i = 0; i < aux; i++) {
                pedido.add(jTextField_pizza1.getText());
            }
        }
        if (!pizza2.isEmpty()) {
            
            int aux = jComboBox_qtd2_pizza.getSelectedIndex()+1;
            valor = valor + 30*aux;  
            for (int i = 0; i < aux; i++) {
                pedido.add(jTextField_pizza2.getText());
            }
        }
        if (!refri.isEmpty()) {
            
            int aux = jComboBox_qtd_refri.getSelectedIndex()+1;
            valor = valor + 10*aux;
            for (int i = 0; i < aux; i++) {
                pedido.add(jTextField_refri.getText());
            }
        }
        if (!sobre.isEmpty()) {
            
            int aux = jComboBox_qtd_sobremesa.getSelectedIndex()+1;
            valor = valor + 7*aux;
            for (int i = 0; i < aux; i++) {
                pedido.add(jTextField_sobremesa.getText());
            }
        }
        
        //criando um novo pedido
        Pedido p = new Pedido();
        p.setObservacao(obs);
        p.setPedido(pedido);
        p.setValor(valor);
        
        //passando o pedido criado para o BD, atraves da função inserirPedido
        PedidoDAO pdao = new PedidoDAO();
        if (pdao.inserirPedido(p)) {
            System.out.println("okInserir");
        }
        
        //setando o id do pedido no JAVA, pois como no BD, o id é auto_increment
        //é realizada a busca do mesmo após a inserção para setar o id certo no JAVA
        if (pdao.buscaIdPedido() != 0) {
            System.out.println("ok");
            p.setIdPedido(pdao.buscaIdPedido());
        }
        //inserção da tabela Mesa_has_Pedido
        if (pdao.inserirMesaPedido(p.getIdPedido(), mesa)) {
            System.out.println("okinserirMesaPe");
        }

        Cliente cli = new Cliente();
        cli.setNome(nome);
        cli.setTelefone(tel);
        cli.setPromoção(promo);
        //preenchendo a tabela cliente no BD
        ClienteDAO clidao = new ClienteDAO();
        if (clidao.inserirCliente(cli, p, mesa)) {
            System.out.println("okinserirCLi");
        }

        
        limpaCampo();
        voltaAfterPrincipal();
    }
}
