/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.comandapizzaria.telas;

import comandapizzaria.Pedido;
import comandapizzaria.PedidoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class EditaPedido extends javax.swing.JFrame {

    /**
     * Creates new form EditaPedido
     */
    public EditaPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel_editapedido = new javax.swing.JPanel();
        jLabel_editarpedido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_pedido = new javax.swing.JList<>();
        jButton_editar = new javax.swing.JButton();
        jButton_excluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_produto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_qtd = new javax.swing.JComboBox<>();
        jButton_add = new javax.swing.JButton();
        jButton_voltar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_editarpedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_editarpedido.setText("Editar Pedido");

        jScrollPane1.setViewportView(jList_pedido);

        jButton_editar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_editar.setText("Editar");
        jButton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarActionPerformed(evt);
            }
        });

        jButton_excluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_excluir.setText("Excluir");
        jButton_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_editapedidoLayout = new javax.swing.GroupLayout(jPanel_editapedido);
        jPanel_editapedido.setLayout(jPanel_editapedidoLayout);
        jPanel_editapedidoLayout.setHorizontalGroup(
            jPanel_editapedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel_editapedidoLayout.createSequentialGroup()
                .addGroup(jPanel_editapedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_editapedidoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel_editarpedido))
                    .addGroup(jPanel_editapedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton_excluir)
                .addContainerGap())
        );
        jPanel_editapedidoLayout.setVerticalGroup(
            jPanel_editapedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_editapedidoLayout.createSequentialGroup()
                .addComponent(jLabel_editarpedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel_editapedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Adicionar Produto");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("nome:");

        jTextField_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_produtoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Quantidade:");

        jComboBox_qtd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox_qtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_qtdActionPerformed(evt);
            }
        });

        jButton_add.setText("Adicionar");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_voltar.setText("Voltar");
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_produto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_add))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_voltar)
                    .addComponent(jButton_add)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_editapedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_editapedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        adicionaProduto();
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jComboBox_qtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_qtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_qtdActionPerformed

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
        voltarAfterPrincipal();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jTextField_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_produtoActionPerformed

    private void jButton_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_excluirActionPerformed
        excluirPedido();
    }//GEN-LAST:event_jButton_excluirActionPerformed

    private void jButton_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarActionPerformed
        editarPedido();
    }//GEN-LAST:event_jButton_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditaPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_editar;
    private javax.swing.JButton jButton_excluir;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JComboBox<String> jComboBox_qtd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_editarpedido;
    private javax.swing.JList<String> jList_pedido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_editapedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_produto;
    // End of variables declaration//GEN-END:variables
    
    //função para excluir o pedido do BD
    private void excluirPedido(){
        PedidoDAO pdao = new PedidoDAO();
        //busca o id do pedido em adamento
        int id = pdao.buscaIdPedido();
        //chama a função que o deleta
        pdao.DeletarPedido(id);
        //seta a lista para aparecer nenhum produto
        String[] aux = new String[1];
        aux[0] = "";
        jList_pedido.setListData(aux);
        //volta a tela
        AfterPrincipal ap = new AfterPrincipal();
        ap.setVisible(true);
        dispose();
    }
    //editar alguma coisa no pedido
    private void editarPedido(){
        //pega o nome selecionado na lista
        String produto = jList_pedido.getSelectedValue();
        PedidoDAO pdao = new PedidoDAO();
        //busca o id do mesmo para alteração
        int id = pdao.buscaIdPedido();
        Pedido p = pdao.BuscaParaListar(id);
        //setando o valor do pedido
        if (produto.contains("pizza")) {
            p.setValor(p.getValor()-30);
        }
        if (produto.contains("refri")) {
            p.setValor(p.getValor()-10);
        }
        if (produto.contains("sobremesa")) {
            p.setValor(p.getValor()-7);
        }
        //manuseio da String do BD, para manipulaçao no JAVA
        String[] aux = new String[p.getPedido().size()];
        for (int i = 0; i < aux.length; i++) {
            aux[i] = p.getPedido().get(i);
        }
        String aux2 = "";
        for (int i = 0; i < aux.length; i++) {
            aux2 = aux2 + aux[i];
        }
        String[] produtos = aux2.split("/");
        String aux3 = "";
        int x = 0;
        //preenchendo o pedido sem o item selecionado
        for (int i = 0; i < produtos.length; i++) {
            if (produtos[i].contains(produto)) {
                //variavel x, serve como um contador, que quando maior que 1
                //ou seja, quando um produto é repetido mais de 1 vez, o produto
                //seja registrado novamente, pois voce só esta fazendo alteração de 
                //um unico produto selecionado
                x++;
                if (x>1) {
                    aux3 = aux3 +"/"+ produtos[i];
                }
            }
            else{
                aux3 = aux3 +"/"+ produtos[i];
            }
        }
        //entrada do nome do novo produto
        String pe = JOptionPane.showInputDialog("Digite nome do produto certo!");
        //setando o novo valor
        if (pe.contains("pizza")) {
            p.setValor(p.getValor()+30);
        }
        if (pe.contains("refri")) {
            p.setValor(p.getValor()+10);
        }
        if (pe.contains("sobremesa")) {
            p.setValor(p.getValor()+7);
        }
        aux3 = aux3 +"/"+ pe;
        //atualização do pedido
        pdao.atualizarPedido(id, aux3, p.getValor());
        
        voltarAfterPrincipal();
    }
    //volta a tela
    private void voltarAfterPrincipal(){
        AfterPrincipal ap = new AfterPrincipal();
        ap.setVisible(true);
        dispose();
    } 
    //função  que lista os produtos cadastrados no BD
    public void listarProdutos(){
        PedidoDAO pdao = new PedidoDAO();
        int id = pdao.buscaIdPedido();
        Pedido p = pdao.BuscaParaListar(id);
        String[] aux = new String[p.getPedido().size()];
        for (int i = 0; i < aux.length; i++) {
            aux[i] = p.getPedido().get(i);
        }
        String aux2 = aux[0];
        for (int i = 1; i < aux.length; i++) {
            aux2 = aux2 + aux[i];
        }
        String[] list = aux2.split("/");
        String t = Float.toString(p.getValor());
        jList_pedido.setListData(list); 
    }
    //adicionando produto no BD
    private void adicionaProduto(){
        PedidoDAO pdao = new PedidoDAO();
        Pedido p = new Pedido();
        int id = pdao.buscaIdPedido();
        p = pdao.BuscaParaListar(id);
        
        String[] aux = new String[p.getPedido().size()];
        for (int i = 0; i < aux.length; i++) {
            aux[i] = p.getPedido().get(i);
        }
        
        String aux2 = aux[0];
        for (int i = 1; i < aux.length; i++) {
            aux2 = aux2 + aux[i];
        }
        //setando o novo valor, com a adição do produto
        int qtd = jComboBox_qtd.getSelectedIndex()+1;
        float valor = p.getValor();
        if (jTextField_produto.getText().contains("pizza")) {
            valor = valor + 30*qtd;
        }
        if (jTextField_produto.getText().contains("refri")) {
            valor = valor + 10*qtd;
        }
        if (jTextField_produto.getText().contains("sobremesa")) {
            valor = valor + 7*qtd;
        }
        for (int i = 0; i < qtd; i++) {
            aux2 = aux2 + "/" + jTextField_produto.getText();
        }
        //chamando a função para atualizar no BD
        pdao.atualizarPedido(id, aux2, valor);
        //listando como está o pedido em andamento
        listarProdutos();
    }
    
}
