/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.comandapizzaria.telas;

/**
 *
 * @author Lucas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_pizzaline = new javax.swing.JLabel();
        jLabel_mesas = new javax.swing.JLabel();
        jButton_mesa01 = new javax.swing.JButton();
        jButton_mesa02 = new javax.swing.JButton();
        jButton_mesa03 = new javax.swing.JButton();
        jButton_mesa04 = new javax.swing.JButton();
        jButton_mesa05 = new javax.swing.JButton();
        jButton_mesa06 = new javax.swing.JButton();
        jButton_mesa07 = new javax.swing.JButton();
        jButton_mesa08 = new javax.swing.JButton();
        jButton_mesa09 = new javax.swing.JButton();
        jLabel_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setSize(new java.awt.Dimension(300, 500));
        getContentPane().setLayout(null);

        jLabel_pizzaline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pizzaline.png"))); // NOI18N
        getContentPane().add(jLabel_pizzaline);
        jLabel_pizzaline.setBounds(20, 10, 270, 130);

        jLabel_mesas.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_mesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_mesas.setText("MESAS");
        getContentPane().add(jLabel_mesas);
        jLabel_mesas.setBounds(80, 150, 130, 29);

        jButton_mesa01.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jButton_mesa01.setText("01");
        jButton_mesa01.setMaximumSize(new java.awt.Dimension(73, 70));
        jButton_mesa01.setPreferredSize(new java.awt.Dimension(70, 70));
        jButton_mesa01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mesa01ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mesa01);
        jButton_mesa01.setBounds(30, 200, 70, 70);

        jButton_mesa02.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jButton_mesa02.setText("02");
        jButton_mesa02.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton_mesa02.setPreferredSize(new java.awt.Dimension(70, 70));
        jButton_mesa02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mesa02ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mesa02);
        jButton_mesa02.setBounds(120, 200, 70, 70);

        jButton_mesa03.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jButton_mesa03.setText("03");
        jButton_mesa03.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton_mesa03.setPreferredSize(new java.awt.Dimension(70, 70));
        jButton_mesa03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mesa03ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mesa03);
        jButton_mesa03.setBounds(210, 200, 70, 70);

        jButton_mesa04.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jButton_mesa04.setText("04");
        jButton_mesa04.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton_mesa04.setPreferredSize(new java.awt.Dimension(70, 70));
        jButton_mesa04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mesa04ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mesa04);
        jButton_mesa04.setBounds(30, 300, 70, 70);

        jButton_mesa05.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jButton_mesa05.setText("05");
        jButton_mesa05.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton_mesa05.setPreferredSize(new java.awt.Dimension(70, 70));
        jButton_mesa05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mesa05ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mesa05);
        jButton_mesa05.setBounds(120, 300, 70, 70);

        jButton_mesa06.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jButton_mesa06.setText("06");
        jButton_mesa06.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton_mesa06.setPreferredSize(new java.awt.Dimension(70, 70));
        jButton_mesa06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mesa06ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mesa06);
        jButton_mesa06.setBounds(210, 300, 70, 70);

        jButton_mesa07.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jButton_mesa07.setText("07");
        jButton_mesa07.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton_mesa07.setPreferredSize(new java.awt.Dimension(70, 70));
        jButton_mesa07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mesa07ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mesa07);
        jButton_mesa07.setBounds(30, 400, 70, 70);

        jButton_mesa08.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jButton_mesa08.setText("08");
        jButton_mesa08.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton_mesa08.setPreferredSize(new java.awt.Dimension(70, 70));
        jButton_mesa08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mesa08ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mesa08);
        jButton_mesa08.setBounds(120, 400, 70, 70);

        jButton_mesa09.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jButton_mesa09.setText("09");
        jButton_mesa09.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton_mesa09.setPreferredSize(new java.awt.Dimension(70, 70));
        jButton_mesa09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mesa09ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mesa09);
        jButton_mesa09.setBounds(210, 400, 70, 70);

        jLabel_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabel_fundo);
        jLabel_fundo.setBounds(0, 0, 300, 500);

        setSize(new java.awt.Dimension(316, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_mesa05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mesa05ActionPerformed
        chamarAfterPrincipal(5);
    }//GEN-LAST:event_jButton_mesa05ActionPerformed

    private void jButton_mesa06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mesa06ActionPerformed
        chamarAfterPrincipal(6);
    }//GEN-LAST:event_jButton_mesa06ActionPerformed

    private void jButton_mesa03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mesa03ActionPerformed
        chamarAfterPrincipal(3);
    }//GEN-LAST:event_jButton_mesa03ActionPerformed

    private void jButton_mesa07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mesa07ActionPerformed
        chamarAfterPrincipal(7);
    }//GEN-LAST:event_jButton_mesa07ActionPerformed

    private void jButton_mesa08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mesa08ActionPerformed
        chamarAfterPrincipal(8);
    }//GEN-LAST:event_jButton_mesa08ActionPerformed

    private void jButton_mesa09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mesa09ActionPerformed
        chamarAfterPrincipal(9);
    }//GEN-LAST:event_jButton_mesa09ActionPerformed

    private void jButton_mesa04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mesa04ActionPerformed
        chamarAfterPrincipal(4);
    }//GEN-LAST:event_jButton_mesa04ActionPerformed

    private void jButton_mesa02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mesa02ActionPerformed
        chamarAfterPrincipal(2);
    }//GEN-LAST:event_jButton_mesa02ActionPerformed

    private void jButton_mesa01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mesa01ActionPerformed
        chamarAfterPrincipal(1);
    }//GEN-LAST:event_jButton_mesa01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_mesa01;
    private javax.swing.JButton jButton_mesa02;
    private javax.swing.JButton jButton_mesa03;
    private javax.swing.JButton jButton_mesa04;
    private javax.swing.JButton jButton_mesa05;
    private javax.swing.JButton jButton_mesa06;
    private javax.swing.JButton jButton_mesa07;
    private javax.swing.JButton jButton_mesa08;
    private javax.swing.JButton jButton_mesa09;
    private javax.swing.JLabel jLabel_fundo;
    private javax.swing.JLabel jLabel_mesas;
    private javax.swing.JLabel jLabel_pizzaline;
    // End of variables declaration//GEN-END:variables

    //função para chamar a tela depois da principal, apos selecionada uma mesa
    //sendo a variavel mesa, o id da mesma para passar os dados para o BD
    private void chamarAfterPrincipal(int mesa){
        AfterPrincipal ap = new AfterPrincipal();
        ap.mesa = mesa;
        ap.setVisible(true);
        dispose();
    }
}
